### ISSUE TITLE
关于ui项目中微服务的问题

### ISSUE THREAD

**Issue by SuperSnowYao** [q315523275/FamilyBucket-UI#1]
VUE用着不是很熟悉，对于UI项目中微服务的这部分功能实现，可否提供一下ASP.NET CORE MVC的实现呢？或者提供一下实现思路。谢谢。

**Comment by q315523275** [comment]
@SuperSnowYao  应用是mvvm的形式，都是通过webapi进行操作，可以查看https://www.cnblogs.com/tianxiangzhe/p/10365178.html 应用部署介绍
